services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./mariadb.env
    restart: always

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    ports:
      - "8080:80"
    restart: always
