apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpadmin
spec:
  selector:
    matchLabels:
      app: phpadmin
  template:
    metadata:
      labels:
        app: phpadmin
    spec:
      containers:
      - image:  phpmyadmin:latest
        name:  phpadmin
        env:
        - name: PMA_ARBITRARY
          value: "1"
        - name: PMA_HOST
          value: mariadb-service
        ports:
        - containerPort: 80
      
---

apiVersion: v1
kind: Service
metadata:
  name:  phpadmin-service
spec:
  selector:
    app:  phpadmin
  type: ClusterIP
  ports:
  - name:  http
    port:  8080
    targetPort:  80